### ISSUE TITLE
CastCollideOnly same table reference 

### ISSUE THREAD

**Issue by hatmatty** [raphtalia/Luanoid#1]
In CastCollideOnly I think the tempFilter should be assigned to a cloned version of the self.RaycastParams.FilterDescendantsInstances. They're both referencing the same table so when you set the self.RaycastParams.FilterDescendantsInstances back to originalFilter it still has all of the same added instances from tempFilter.

**Comment by raphtalia** [comment]
When reading `RaycastParams.FilterDescendantsInstance` it returns a new table reference each time. I decided to write a test for this case anyway though just to be safe.
![image](https://user-images.githubusercontent.com/59540801/166976068-becdbf29-8631-4551-9710-2545f900b703.png)

**Comment by hatmatty** [comment]
Oh I see, didn't realize it did that. Sorry for the bother.
