### ISSUE TITLE
Character sometimes fails to load in example builds

### ISSUE THREAD

**Issue by raphtalia** [raphtalia/Luanoid#10]
In the builds found in the `examples` directory, the client's character sometimes fails to load the Luanoid.

**Comment by DrewBokman** [comment]
It's caused by PlayerModule's Control module hanging when it's called, I haven't look much farther past that.

**Comment by DrewBokman** [comment]
ive found the cause 
![image](https://user-images.githubusercontent.com/61132894/179126846-99e13316-7027-41fa-b94e-538cb73bfbb9.png)

**Comment by raphtalia** [comment]
Thank you for finding the cause. Should be fixed now.
