### ISSUE TITLE
Luanoid:MoveTo

### ISSUE THREAD

**Issue by philhogg** [raphtalia/Luanoid#3]
Having deployed the code, and got Luanoids into the experience, running :MoveTo(Vector3.new(0,0,0) does not do anything with the Luanoid (they just spawn, fall to the ground where the rootpart collides with the baseplate). 

I'm using the serverside module to create NPCs.

**Comment by raphtalia** [comment]
Did you call `Luanoid.CharacterController:Start()`?

**Comment by philhogg** [comment]
Ah sorry, yes I missed that from the demo files. They move now (but lots of errors about missing animations - but that's just probably because I've not copied across something. Thanks
