### ISSUE TITLE
:ApplyDescription Failing with Headless

### ISSUE THREAD

**Issue by DrewBokman** [raphtalia/Luanoid#4]
"face is not a valid member of MeshPart "Workspace.Player.Head"

Headless lacks the face object, id suggest making a fallback so issues don't continue to arise.

![image](https://user-images.githubusercontent.com/61132894/176839612-f9f0f745-9606-42ec-9fa1-8cd6ec9d1451.png)

**Comment by raphtalia** [comment]
4cef7692b8ad845b73dba2b7b12ce212c84138fa prevents the error.

However, this error only occurs if calling `ApplyDescription()` with no 2nd argument for changing the rig as this is intended for only updating attributes such as body color and clothing. This results in a rig with a visible head but no face. I'd rather not make an exception for updating the head mesh with the headless mesh.

Any feedback before I merge and close this issue?

**Comment by DrewBokman** [comment]
Commit looks good, If I stumble across anything else i'll open up another issue.
